# Generated by Django 3.2.8 on 2021-12-15 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import orden.comun


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carts', '0001_initial'),
        ('apps', '0001_initial'),
        ('products', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordenID', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[(orden.comun.OrdenStatus['CREATED'], 'CREATED'), (orden.comun.OrdenStatus['PAYED'], 'PAYED'), (orden.comun.OrdenStatus['COMPLETED'], 'COMPLETED'), (orden.comun.OrdenStatus['CANCELED'], 'CANCELED')], default='En Espera', max_length=40)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('pagado', models.CharField(choices=[(orden.comun.OrdenStatus['CREATED'], 'CREATED'), (orden.comun.OrdenStatus['PAYED'], 'PAYED'), (orden.comun.OrdenStatus['COMPLETED'], 'COMPLETED'), (orden.comun.OrdenStatus['CANCELED'], 'CANCELED')], default='No', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.cart')),
                ('id_cart', models.ForeignKey(blank=True, db_column='id_cart_p', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carts.cart')),
                ('id_products', models.ForeignKey(blank=True, db_column='id_products_p', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.product')),
                ('id_reserva', models.ForeignKey(blank=True, db_column='id_reserva_p', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='apps.reserva')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
