# Generated by Django 3.2.8 on 2021-12-15 00:01

from django.db import migrations, models
import orden.comun


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0002_auto_20211211_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='pagado',
            field=models.CharField(choices=[(orden.comun.OrdenStatus['CREATED'], 'CREATED'), (orden.comun.OrdenStatus['PAYED'], 'PAYED'), (orden.comun.OrdenStatus['COMPLETED'], 'COMPLETED'), (orden.comun.OrdenStatus['CANCELED'], 'CANCELED')], default='No', max_length=40),
        ),
    ]
