# Generated by Django 3.2.8 on 2021-12-19 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0002_auto_20211217_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='pagado',
            field=models.CharField(choices=[('En espera', 'En espera'), ('Pagado', 'Pagado'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado'), ('No', 'No'), ('Si', 'Si')], default='No', max_length=40),
        ),
        migrations.AlterField(
            model_name='orden',
            name='status',
            field=models.CharField(choices=[('En espera', 'En espera'), ('Pagado', 'Pagado'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado'), ('No', 'No'), ('Si', 'Si')], default='En Espera', max_length=40),
        ),
    ]
