# Generated by Django 3.2.8 on 2021-12-15 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('codename', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True, unique=True)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True)),
                ('action_flag', models.IntegerField()),
                ('change_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(blank=True, null=True)),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id_bodega', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('total_producto', models.CharField(max_length=200)),
                ('total_merma', models.CharField(max_length=100)),
                ('categoria_producto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id_mesa', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('numero_mesa', models.BigIntegerField()),
                ('disponibilidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('rut_proveedor', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=40)),
                ('direccion_proveedor', models.CharField(max_length=40)),
                ('codigo_postal', models.BigIntegerField()),
                ('ciudad', models.CharField(max_length=20)),
                ('pais', models.CharField(max_length=20)),
                ('telefono_proveedor', models.CharField(max_length=20)),
                ('email_proveedor', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='SolicPed',
            fields=[
                ('id_soli_prod', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('producto_pedir', models.CharField(max_length=100)),
                ('cantidad', models.CharField(max_length=100)),
                ('fecha_solicitud', models.DateField()),
                ('hora_solicitud', models.DateTimeField()),
                ('fecha_entrega', models.DateField()),
                ('hora_entrega', models.DateTimeField()),
                ('estado_solicitud', models.CharField(max_length=100)),
                ('auth_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='apps.authuser')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cantidad_personas', models.BigIntegerField()),
                ('fecha_reserva', models.DateTimeField()),
                ('comentario', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_vence', models.DateTimeField()),
                ('auth_user', models.ForeignKey(blank=True, db_column='AUTH_USER_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='apps.authuser')),
                ('mesa_id_mesa', models.ForeignKey(blank=True, db_column='mesa_id_mesa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='apps.mesa')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('cantidad', models.CharField(max_length=40)),
                ('temperatura_conservacion', models.FloatField()),
                ('fecha_caducidad', models.DateField()),
                ('zona_conservacion', models.CharField(max_length=40)),
                ('tipo_alimento', models.CharField(max_length=40)),
                ('bodega_id_bodega', models.ForeignKey(blank=True, db_column='bodega_id_bodega', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apps.bodega')),
                ('proveedor_rut_proveedor', models.ForeignKey(blank=True, db_column='proveedor_rut_proveedor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apps.proveedor')),
                ('solic_ped_id_soli_prod', models.ForeignKey(blank=True, db_column='solic_ped_id_soli_prod', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apps.solicped')),
            ],
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id_boleta', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha_emision', models.DateTimeField()),
                ('subtotal', models.BigIntegerField()),
                ('auth_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='apps.authuser')),
            ],
        ),
    ]
