# Generated by Django 3.2.8 on 2021-12-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartsCart',
            fields=[
                ('id_cart', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cart_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField()),
                ('user_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'carts_cart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CartsCartproduct',
            fields=[
                ('id_cartproduct', models.BigIntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'carts_cartproduct',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriesCategory',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=40, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'categories_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriesCategoryProducts',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'categories_category_products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenOrden',
            fields=[
                ('id_orden', models.BigIntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=40, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=9)),
                ('created_at', models.DateTimeField()),
                ('user_id', models.IntegerField()),
                ('ordenid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('detalle', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'orden_orden',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductsProduct',
            fields=[
                ('id_producto', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('tiempo', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField()),
                ('slug', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'products_product',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='Plato',
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={},
        ),
    ]
