# Generated by Django 3.2.8 on 2021-11-03 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id_boleta', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha_emision', models.DateTimeField()),
                ('subtotal', models.BigIntegerField()),
            ],
            options={
                'db_table': 'boleta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id_caja', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'caja',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Factura',
        ),
        migrations.DeleteModel(
            name='Finanza',
        ),
        migrations.DeleteModel(
            name='TipoTrab',
        ),
        migrations.DeleteModel(
            name='Trabajador',
        ),
    ]
