# Generated by Django 3.2.8 on 2021-12-10 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20211209_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='direccion_rest',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='nombre_rest',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='telefono',
        ),
        migrations.AlterModelTable(
            name='restaurant',
            table=None,
        ),
    ]
