# Generated by Django 3.2.8 on 2021-12-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20211215_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='valor',
            field=models.IntegerField(null=True),
        ),
    ]
