# Generated by Django 3.2.8 on 2021-12-17 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20211217_1551'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientes',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.producto'),
        ),
    ]
